//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shrzvdcghblt21
        ///sixdddkcqjdnzzrgfourxjtwosevenhg9
        ///threevt1onegxgvc9flk
        ///7dmqzksnlcpbsqkzqlfour1four
        ///4seven9gdlnhqxfseven94five
        ///nldeightwoshgnsjnzmbkbxcxltsqtstrgdmvqvxbfour6six
        ///87mmlvfr4
        ///six1vvrlxx8two
        ///znmfvdlhvjtwo9three4tzjqcfcgnsevenccvnsjczlpm
        ///5sixninesixnh
        ///three1tbtwo
        ///five9seventwobqsjqzxkptkhsix1
        ///74fivemn
        ///sevenfivetsglnine8three
        ///spnvnfkbv4eightlmdkxmsfour574eight
        ///one4four2fivedcpqjmgc8
        ///two6sevensix33
        ///krc34five
        ///doneight64qgc251four7
        ///vpjthc6
        ///threethxbtffhbfourfive3
        ///onetwo5
        ///1sevenngjq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 1: 10 green, 9 blue, 1 red; 1 red, 7 green; 11 green, 6 blue; 8 blue, 12 green
        ///Game 2: 11 red, 7 green, 3 blue; 1 blue, 8 green, 5 red; 2 red, 12 green, 1 blue; 10 green, 5 blue, 7 red
        ///Game 3: 2 red, 7 green, 1 blue; 1 blue, 8 red; 7 green, 19 red, 5 blue; 1 blue, 10 green, 18 red; 10 red, 6 blue, 4 green
        ///Game 4: 2 blue, 5 green, 2 red; 7 red, 3 green; 3 blue, 2 red; 16 green, 2 blue
        ///Game 5: 1 blue, 9 red; 5 blue, 9 green, 6 red; 8 red, 10 blue, 3 green; 3 red, 13 green, 4 blue; 5 green, 9 red, 6 b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .....................................164.................429.35...........221....................................................34.........
        ///........................464...........*.................................../.......53*.....954.763.....................114*.764..............
        ///223............275.....................725.....$.........460....176............................*............+.................&amp;.267.........
        ///.........854..........919.798...............541.....302...................723......$.. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day03 {
            get {
                return ResourceManager.GetString("Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card   1: 61 73 92 28 96 76 32 62 44 53 | 61 17 26 13 92  5 73 29 53 42 62 46 96 32 21 97 99 28 12  4  7 44 19 71 76
        ///Card   2:  3 88 36 12  2  9 15 55 21 89 | 23 39 98 36  2 24  9  3 78 95 55 37 12 61 38 88 85 89 13 15 96 45 21 25 30
        ///Card   3: 96 44 52 56 82 89 73 50  9 68 | 39 71 64 32 13 57 56 67 34 84 51 53 41 16 38 63  5 80 70 75  7 76 85 83 18
        ///Card   4: 54 84 76 44 38 33 12 17 93 94 | 18 21 53 11  7 98 78 92  9 32 29 50 86 23 95 77 22 79 71 80 60 35 54 36 91
        ///Card   5:  8 11 33 98 37 80 39 76 53 91  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day04 {
            get {
                return ResourceManager.GetString("Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seeds: 2637529854 223394899 3007537707 503983167 307349251 197383535 3543757609 276648400 2296792159 141010855 116452725 5160533 2246652813 49767336 762696372 160455077 3960442213 105867001 1197133308 38546766
        ///
        ///seed-to-soil map:
        ///1024364543 1121869540 764570177
        ///1788934720 0 30748436
        ///710359306 576061773 314005237
        ///1819683156 509305212 66756561
        ///478556776 890067010 231802530
        ///0 30748436 478556776
        ///
        ///soil-to-fertilizer map:
        ///3998185854 3762642503 103735883
        ///2968507762 2068943953 132922295
        ///1615660383 31282 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day05 {
            get {
                return ResourceManager.GetString("Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:        49     97     94     94
        ///Distance:   263   1532   1378   1851.
        /// </summary>
        public static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32T3J 893
        ///A9942 54
        ///J57Q8 571
        ///779TK 931
        ///69696 457
        ///Q55Q5 478
        ///99399 735
        ///TA756 782
        ///QQQKQ 838
        ///QTJJA 995
        ///J7T7T 8
        ///22792 790
        ///588K8 376
        ///J77KT 191
        ///72T29 575
        ///58585 196
        ///58535 394
        ///263K5 566
        ///ATAAA 352
        ///7K7AK 477
        ///A3829 14
        ///22349 954
        ///KT647 244
        ///84848 208
        ///82A8A 77
        ///3A383 698
        ///97788 820
        ///QQ4Q7 991
        ///67Q66 837
        ///73QQ7 879
        ///Q4Q5Q 69
        ///Q5Q33 767
        ///585TT 52
        ///5K859 943
        ///238A3 170
        ///48887 668
        ///QAQQQ 591
        ///A8755 666
        ///4AK62 157
        ///4A9J4 350
        ///TJAAA 280
        ///AT9T9 592
        ///7Q497 390
        ///56748 681
        ///9425A 414
        ///5357J 737
        ///5QQQQ 597
        ///38 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day07 {
            get {
                return ResourceManager.GetString("Day07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRRLRRRLLRRRLRRRLLRRLRRRLRRLRRLRLRLRLRLRLLRRRLRRLRLRRRLRRRLRLRRRLRLRRLRRRLRRRLRLLRRRLRLLLRLRRRLRLRRLRRLLLLRRLRRLRLRLRRLRLRRLRRRLRRRLRLRLRRLLLLRRLRLRRLLRRRLRLRLRLRRRLRLLLRLRLRRRLRLRRRLRRRLRRRLLRRLRRRLRRRLRRRLRRRLRLLRRRLRLRRRLRLRLRRRLRRLRRLLRRRLRRRLRRRLRLRLRLRRLRRRLRRLRLRLRLRRRR
        ///
        ///TJF = (TXF, NGK)
        ///PDL = (TXD, FRT)
        ///MVB = (HLF, BMQ)
        ///LKG = (JTG, THR)
        ///MPN = (CKC, FKR)
        ///HHN = (HFV, FGD)
        ///TMM = (GJG, CCJ)
        ///HJD = (PHB, FJM)
        ///JNC = (NMB, SND)
        ///HHR = (NBB, HMD)
        ///KCC = (BHB, PDC)
        ///CKN = (FRD, TQK)
        ///NCG = (VSC, PTD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day08 {
            get {
                return ResourceManager.GetString("Day08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54
        ///12 27 47 68 92 149 343 943 2562 6504 15418 34500 73686 151710 303812 596709 1157888 2232401 4290657 8227316 15717112
        ///-1 12 52 135 290 585 1167 2315 4511 8546 15696 28027 48918 83927 142167 238407 396167 652136 1062308 1710303 2718418
        ///5 20 41 73 130 249 514 1092 2286 4613 8918 16538 29533 51004 85521 139687 222867 348114 533327 802679 1188356
        ///4 -1 -6 -11 -16 -21 -26 -31 -36 -41 -46 -51 -56 -61 -66 -71 -76 -81 -86 -91 -96
        ///17 19 24 49 132 341  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day09 {
            get {
                return ResourceManager.GetString("Day09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF-7F-7.|FJ7L-7-.FL-F7|-7FFF77J.|7F--J-FF7-L..-7FF-LF7F|-F|7-L-FLJ7-FF-JFF-7-7.-J-.--7.-F---FJ-|..-J7.|J-77-F7---77FFLJ7.LFJF7.FL|-J--7-LJ-|
        ///J.-L-JF-L7J|LL|7FL7LL||.LJ--J7JFL|J7|7.JLJ|L-L7L7-7J|L7|L||..|7L.L7.FL7-L--L-JLJ..FLJ|F7L|7-JJ-LLLJJLF..F77FLJ7FF7-L7|-L7-|7|.FFJJJ7L-LJ|..J
        ///||..L7.LL-7J-.F77F7JF|--L.|7LJ-J.L-FF7J...|||JFJLJ7.L-L77L|.7.||7-J7J7LFJ.7F||-|.7LL77.JLJJ7|F|F|..F.|.FLLL-.---F-7.F7J.7-JLL7--77.|FFJ.7F7J
        ///F-7J.L-7LFJJ7.LF-F77.|LFLFFJ|JJL7JLL|JLF--7J7-L.|FJ.LF-J--L-|.L7LL|7.-J|L|--F7JL7L.LLJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .............................................................................................#..............................................
        ///...#....................#............................#......................#........................#...........#................#.........
        ///................#.....................................................#..............#.....................#................................
        ///................................................................#..................... [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#?.##??.?? 2,2,1
        ///?.#?#?????.? 1,1,3
        ///??##??????????.?# 4,4,2
        ///..#?????.?#?.#?. 2,2,1,2
        ///????????????##?? 1,1,1,1,3
        ///?????.#????#??? 1,1,3,2,1
        ///.?#..?#?????#?? 1,2,5
        ///?#??????????????.? 4,1,2,2,1
        ///#??##?.#??. 1,2,3
        ///???????#??????#.?? 13,1
        ///?#..#??.?#.? 2,1,1,2
        ///?.###??????#???.?.?? 11,1
        ///.?????????#???. 3,7
        ///?????.#??????#.? 1,1,5,2
        ///?#???????? 4,4
        ///?.??.#.????#??#??? 1,1,1,4,1,1
        ///??.?????.#?.?#?????. 1,3,1,2,3,3
        ///.???#?????.?? 4,1,1,1
        ///??#??.#??.?? 3,2,2
        ///.???.?###. 1,4
        ///#.???##?#? 1,6
        ///#.??????#?.??. 1, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .####..#.#.#.##..
        ///........#..##....
        ///..##..#.....#..##
        ///......##.##.#####
        ///######.#.####....
        ///..##....#..##.#..
        ///.#..#..#####.#...
        ///..##...#..#...#.#
        ///#######.#....####
        ///
        ///#.###..####
        ///..#####....
        ///#.##...####
        ///##..#.##..#
        ///##.#.##.##.
        ///##.#.##.##.
        ///##..#.##..#
        ///#.##...####
        ///..###.#....
        ///#.###..####
        ///.##....#..#
        ///
        ///.##...#...#####
        ///...######..#.#.
        ///..#.#..#.####..
        ///#..#...##.##..#
        ///#..#...##.##..#
        ///..#.#..#.####..
        ///#..######..#.#.
        ///.##...#...#####
        ///#..#..#.#...#.#
        ///####.#####..#..
        ///....#.##..##...
        ///#..#### [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.O#....O.O...O..OO#OO##..O..##...#..........OO..#.OO...................O..O##.#OOO...O#.#.#.O.O#OO.
        ///.O..OO..O.O..O......OO.#....#O#.#.#.#.#.O.OO...#.O#.OOO.#.#.#.OO..#.#O...O.O.O.O#.#.O.O....#..O#O...
        ///O....#..O..O.OO..#OO.O.....O#OOO..#.#......O...#..#..O......#O.#.O.#.O...#.#.#.........O#.......#OO.
        ///......O.O##......###OO#..O#.#...O...O.....##.........#.OO.#........#OO.O....###...#.##..O........O.#
        ///#.OO.....OOO....O.....OO.OOO..#O.OO...#...O......OO###........O..#.#.O..O......O#...O.....#.#...##..
        ///#. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day14 {
            get {
                return ResourceManager.GetString("Day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tp-,pnm-,vrg-,nfk=6,qqc=2,zs=2,hm-,xnl=4,fszj=6,cx=7,zpfsz-,hdg=9,nqqm-,nfk-,pb-,cbn=5,ng=8,pdk=4,rd=7,sl=2,qtk=7,fkdp-,dxkx-,qc=9,dxtz-,bgzmkc-,jzv-,ljd-,nbh=7,dtr-,sbd=5,zt=2,zgj-,rbpq=7,vm=6,gq=3,qnjfm-,hxd=8,rsnbql=4,bdx=7,mvgfg=8,hv=4,ql=5,tnkt-,qdh-,dv-,dqclp-,tnc=2,vgk=7,rb=6,flzg=6,rv=5,qn-,fgdr-,gj=5,gg-,vtm-,btjv=5,xs-,rfbn-,hxd=6,bhxnh-,zr-,llq=7,ds-,xs-,hdvdp=1,ll=9,kgm=1,tj-,lmx=3,mn-,zbb-,xj-,pcv=1,xrl=7,mc=2,zf=3,rrl=7,mztj=2,pcp-,fvjj=6,tn=9,jc-,xsr=2,kkgj-,bnzq=7,vtld-,hx-,zs=5,fl-,pmjz-,hh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day15 {
            get {
                return ResourceManager.GetString("Day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \......../......../.............\..-................||.......|.-./....|.|/................|\...-.......\\..-..
        ///.../.........\................\.-.........\...\........................./\................-......\.........|.-
        ///-\......................../...\........................\....-.....................................|...........
        ///|.../......\......................\/..-...|.\..............-.............../....|..../........|............\..
        ///......../..................-....................././............ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day16 {
            get {
                return ResourceManager.GetString("Day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 322222331232132221112333141131141421432535111315454231154425333445331325214334352425212345343422113421533234333342231121312224211232132331311
        ///112222221132312141233334323313423341313142332514144441221332524235451353431144233453551355535521415123254413343222433142441412131232231122221
        ///233311211132123132221413413342313144254415324345245135411343525533355513313524342444244552154352343444341241224233132212231434412321112213132
        ///12212122212313344242224223134112332522521325444324524152212313353132355553223315153 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day17 {
            get {
                return ResourceManager.GetString("Day17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R 4 (#2dbea0)
        ///U 7 (#771413)
        ///R 5 (#991f00)
        ///U 4 (#0db993)
        ///R 3 (#1c6ab0)
        ///D 11 (#67d2f3)
        ///R 4 (#778c30)
        ///U 3 (#7535c3)
        ///R 2 (#2afd02)
        ///U 3 (#84a633)
        ///R 5 (#7d6492)
        ///U 7 (#236953)
        ///R 4 (#4598b2)
        ///U 5 (#5c4bc3)
        ///R 7 (#2f17b2)
        ///U 4 (#76bf51)
        ///R 5 (#701390)
        ///U 8 (#388c61)
        ///L 5 (#701392)
        ///D 5 (#550f91)
        ///L 6 (#3dc292)
        ///U 5 (#43af93)
        ///L 8 (#311ed2)
        ///U 5 (#574df3)
        ///R 9 (#21efb2)
        ///U 4 (#912163)
        ///R 2 (#8a10e2)
        ///D 4 (#83a213)
        ///R 8 (#7a0f52)
        ///U 6 (#2f5653)
        ///L 3 (#17f722)
        ///U 3 (#53bf23)
        ///L 10 (#012322)
        ///U 2 (#48b7b1)
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day18 {
            get {
                return ResourceManager.GetString("Day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kbr{x&gt;2309:A,R}
        ///rp{a&gt;2160:mcm,m&lt;3139:bz,fs}
        ///hqr{a&gt;3048:R,x&gt;1298:R,R}
        ///ht{s&lt;1042:A,a&lt;3744:A,a&gt;3879:lb,zsj}
        ///hkl{x&lt;2690:xps,gsq}
        ///bvk{s&lt;464:R,x&gt;1190:R,a&lt;3443:A,A}
        ///mj{a&lt;725:R,R}
        ///kph{s&lt;385:A,A}
        ///vr{x&gt;1596:xt,nk}
        ///hc{m&lt;999:A,x&lt;224:R,R}
        ///bp{a&gt;1785:msj,sk}
        ///fs{a&lt;1989:A,x&gt;561:kdv,x&gt;192:A,R}
        ///nls{x&gt;3679:R,s&lt;1583:A,s&lt;1669:A,A}
        ///gsq{a&gt;1760:A,A}
        ///phd{a&lt;187:R,a&gt;307:A,s&gt;2783:A,A}
        ///nb{s&lt;238:A,R}
        ///rs{x&lt;2853:cd,a&lt;1366:pxm,m&gt;2215:cfp,bpt}
        ///cvn{m&gt;1940:tb,s&lt;421:tmg,s&gt;560:nnq,A}
        ///fh{x&lt;264:tf,hvg}
        ///kl{x&gt;382:R,s&gt;1772:R,s&gt;1604 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day19 {
            get {
                return ResourceManager.GetString("Day19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %vg -&gt; lf, vd
        ///%dr -&gt; kg
        ///%cn -&gt; mv, pt
        ///%rq -&gt; bk, gr
        ///%vp -&gt; lp, bk
        ///%kg -&gt; lv
        ///%lv -&gt; jc, tp
        ///%sj -&gt; rm, vd
        ///%jc -&gt; tp, qr
        ///%km -&gt; tp, dr
        ///%jx -&gt; cn
        ///&amp;vd -&gt; tf, lf, nb, cx, hx, lr
        ///%lp -&gt; jt, bk
        ///%vj -&gt; ps
        ///broadcaster -&gt; km, lr, xh, rf
        ///%dj -&gt; pt, gc
        ///%cg -&gt; vd, hx
        ///&amp;ln -&gt; tg
        ///%fl -&gt; pt, sk
        ///%lm -&gt; tr, bk
        ///%lr -&gt; vd, vg
        ///&amp;pt -&gt; vq, rf, cm, jx, rg
        ///%cx -&gt; gp
        ///%gp -&gt; vd, sj
        ///&amp;db -&gt; tg
        ///%st -&gt; vd
        ///%jt -&gt; bk
        ///%jh -&gt; lm, bk
        ///%xf -&gt; bd, tp
        ///%gc -&gt; cm, pt
        ///&amp;tp -&gt; dr, km, kg, db, vj, qr
        ///%ps -&gt; xf, tp
        ///%rf -&gt; p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day20 {
            get {
                return ResourceManager.GetString("Day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...................................................................................................................................
        ///...##......#....#...#.....#.#....#...#...#...#......#........................##......#..#..#.#........#....................##......
        ///...#.......#..........#..#....#................#...##.....##...................#..........###......#.....#.........#....#.#........
        ///........#..##.............#..#...##...#..#...##...............................#.........................#........ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day21 {
            get {
                return ResourceManager.GetString("Day21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7,6,120~8,6,120
        ///7,3,219~9,3,219
        ///2,1,54~4,1,54
        ///3,1,321~5,1,321
        ///7,3,144~9,3,144
        ///1,9,122~4,9,122
        ///8,0,105~8,1,105
        ///3,2,254~3,4,254
        ///9,5,31~9,7,31
        ///9,8,16~9,8,18
        ///6,0,21~8,0,21
        ///2,6,148~2,6,148
        ///3,0,279~3,0,280
        ///0,8,108~0,8,110
        ///1,4,93~1,5,93
        ///2,7,119~3,7,119
        ///2,4,155~5,4,155
        ///3,1,100~3,3,100
        ///2,2,84~2,3,84
        ///3,8,47~4,8,47
        ///5,0,9~5,2,9
        ///1,2,157~1,2,160
        ///7,3,287~8,3,287
        ///5,5,309~5,5,311
        ///2,5,274~2,8,274
        ///4,4,263~5,4,263
        ///4,5,139~7,5,139
        ///6,0,203~9,0,203
        ///6,9,90~7,9,90
        ///2,6,293~2,7,293
        ///4,5,229~4,8,229
        ///1,0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day22 {
            get {
                return ResourceManager.GetString("Day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.###########################################################################################################################################
        ///#.#...###...#.....#...#.....#.....#.......###...#.....#...................###.....#...###...#.......#...#...#.....###...###...#####.........#
        ///#.#.#.###.#.#.###.#.#.#.###.#.###.#.#####.###.#.#.###.#.#################.###.###.#.#.###.#.#.#####.#.#.#.#.#.###.###.#.###.#.#####.#######.#
        ///#.#.#...#.#.#.#...#.#...#...#...#...#...#...#.#.#.#...#.........#...#...#...#...#.# [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day23 {
            get {
                return ResourceManager.GetString("Day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 385803404726014, 386664184220541, 365612177547870 @ -192, -149, -36
        ///67771006464582, 193910554798739, 21517103663672 @ 280, 136, 426
        ///334054450538558, 356919582763697, 188448277532212 @ 84, -25, -48
        ///312676332944619, 337964672568504, 98227917525187 @ -35, -48, 372
        ///262053228716736, 348276320363511, 253216606954466 @ 37, -86, 31
        ///333526091894424, 327836481184227, 164687124486536 @ -65, 10, 196
        ///136308365945474, 334381606808383, 125587682445786 @ 158, -78, 267
        ///323717230671270, 328009829437175, 33711559065609 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day24 {
            get {
                return ResourceManager.GetString("Day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shd: hzh hcz sch rnf
        ///pmk: dpr
        ///hcf: sjt stk plv fjx
        ///kkp: ggq fqq
        ///fhc: mvh
        ///rrx: jjj qht
        ///bhc: grq qmx cdr
        ///kzf: mnc ksm nzj gtt pqq
        ///qhk: hmm jxg qtb
        ///hzp: zrx hst
        ///lss: kzl dzx tjb
        ///jvh: vfj
        ///cnz: tlp
        ///lsx: pbb gsg
        ///jnq: mjk chg dmq dbb
        ///xrf: znm
        ///dpj: zgl dpz flt rfr
        ///ntl: kfg dnm
        ///qhz: fdl
        ///bkv: ptn ldn nlg nch glp
        ///mhg: ngq jjq fvr
        ///fmt: vsm xtb mdj qst
        ///bhl: nmk plc
        ///cqn: dpz
        ///mgn: frj cql
        ///sqq: phd ctg zlx ftn
        ///zvv: xnj
        ///bbn: bmb dmb
        ///sfj: fnb
        ///qkg: jck vzz xlx vrt
        ///dtj: fxl fbf
        ///vgn: qbk qmx
        ///ssd: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day25 {
            get {
                return ResourceManager.GetString("Day25", resourceCulture);
            }
        }
    }
}
